repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint
        entry: poetry run lint
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
      - id: typechecking
        name: Typecheking
        entry: poetry run typecheck
        types: [python]
        language: system
        always_run: true
        pass_filenames: false
