repos:
  - repo: local
    hooks:
      - id: ruff-script
        name: Lint
        entry: python scripts/lint.py
        language: system
        types: [python]
      - id: ty
        name: Typecheking
        entry: python scripts/typecheck.py
        language: system
        types: [ python ]
